spring:
  application:
    name: config-server
  config:
    name: configserver
  cloud:
    config:
      enabled: false
      server:
        git:
          uri: https://github.com/leximus7/spring-cloud-config
#          uri: file:///${user.home}/config-repo
          validate_certificates: false
#          proxy:
#            https:
#              host:
#              password:
#              port: '8080'
#              username:

server:
  port: 8889